#! /bin/bash

if [ $# == 0 ]; then
    echo "The 'book' argument is required."
    exit
fi

echo "Pre-processing files"
cd preprocessing
if [ ! books/$1/Interlinear.xml ]; then
  echo "Building the interlinear (this could take a while)."
  lua create-interlinear.lua $1
fi
lua preprocess.lua $@ && cd ..

echo "Rendering PDF"
sile prepared.xml
# sile prepared.xml -d frames
# sile prepared.xml -d typesetter

if [ ! -d output/$1 ]; then
  mkdir output/$1
fi

mv prepared.xml output/$1/prepared.xml
mv prepared.pdf output/$1/prepared.pdf