#! /bin/bash

if [ $# == 0 ]
then
  echo "The 'book' argument is required."
  exit 1
fi

NEEDS_CONCATENATING=false
for arg in $@
do
  if [ $arg == "--maxChapter" ]
  then
    NEEDS_CONCATENATING=true
  fi
done

echo "Pre-processing files"
cd preprocessing
if [ ! -f ../books/$1/Interlinear.xml ]; then
  echo "Building the interlinear" $1
  lua create-interlinear.lua $1 || exit 1
fi
lua preprocess.lua $@ || exit 1
cd ..

CHAPTERS=$(ls *.xml)

echo "Rendering PDFs"
for CHAPTER in $CHAPTERS
do
  sile -I styles/styles.sil $CHAPTER
  # sile -I styles/styles.sil $CHAPTER -d frames
  # sile -I styles/styles.sil $CHAPTER -d typesetter
done

if [ -d output/$1 ]; then
  rm -r output/$1
fi
mkdir output/$1

if [ $NEEDS_CONCATENATING = "true" ]
then
  echo "Combining PDFs"
  PDFS=$(ls *.pdf | sort -g)
  gs -dNOPAUSE -sDEVICE=pdfwrite -sOUTPUTFILE=$1.pdf -dBATCH $PDFS
fi

mv *.xml output/$1
mv *.pdf output/$1

rm context.lua
